### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by stefanhacks** [cafecomlucas/SlotMock#1]
Olá Lucas, vimos o teste, gostariamos de passar um feedback geral e também apresentar umas dúvidas que apareceram. Fique à vontade para responder.

Vamos lá:

1. Por que você decidiu armazenar o número de [clicks](https://github.com/cafecomlucas/SlotMock/blob/master/assets/scripts/GameManager.ts#L59)? Sacamos que ele é usado na matemática, mas infelizmente não está seguindo a estatística pedida. Gostaria de tentar um refactor ou explicar o que você tentou fazer? 

2. Ainda na mesma função, o Math.random() [da linha 115](https://github.com/cafecomlucas/SlotMock/blob/master/assets/scripts/GameManager.ts#L115) não parece ter um propósito claro. Ficamos confusos com a presença dele.

3. Fora isso, não encontramos referência à geração de logs no repositório, conforme pedido no teste.

No geral, sentimos falta de comentários para entender o seu desenvolvimento, mas o deploy e a execução das animações ficou dez.

**Comment by cafecomlucas** [comment]
Olá Filipe, muito obrigado pelo retorno e pelas dúvidas que levantou. Acho bem legal pois isso me da uma luz sobre onde posso melhorar.

Vamos lá:

### 1. Sobre a estatistica pedida

Talvez eu tenha compreendido a proposta da forma errada. Explicando melhor:

- **Lógica A (o que eu fiz)**: Pelo que tinha entendido, as porcentagens de "tempo" se baseiam no número de vezes que alguém clica. Por exemplo: se eu clico 1 vez, isso equivale a 100% de vezes, se eu clico 2 vezes, cada clique equivale a 50% das vezes clicadas, e assim por diante. Até chegar nos 7% (onde acontece o reset da porcentagem e dos cliques). E o ciclo se repete: mostra 1 linha, depois de um tempo mostra 2 linhas e depois de mais um tempo, 3 linhas novamente. Sendo que nessa lógica todo o cálculo é feito com base em uma única porcentagem (que vai de 100% a 7%), diferente do exemplo seguinte.

- **Lógica B**: A lógica de 50% randomico (porcentagem A) + 50% acertos (porcentagem B) não fez muito sentido pra mim. Por exemplo, eu teria que verificar os 33%, os 10% e os 7% apenas de dentro da porcentagem B? Outra questão: e quando eu alcançar porcentagens fora dessas condições que foram definidas? O que aconteceria? Já que estamos "dentro" da porcentagem B não podemos apresentar resultados randomicos.

Posso fazer um refactory, precisaria apenas de uma explicação complementar para entender melhor a proposta.

### 2. Sobre o Math.random()

Eu tinha começado a refazer a parte randomica até compreender que isso já é feito automáticamente quando passamos o dado 'null' na construção da matriz. Depois de compreender isso eu apaguei o código que tinha começado, porém eu acabei esquecendo de excluir essa linha de código. Então ela não tem motivo pra existir mesmo.

### 3. Sobre a geração de logs

Eu não compreendi muito bem como deveria ser feito, então acabei deixando os logs via console do navegador. A proposta seria fazer a geração de logs na mesma tela do gameplay mesmo? Eu pensei em fazer junto com a tela do gameplay utilizando o ReactJS, mas infelizmente não encontrei uma forma de integrar o React com a geração automática que o Cocos Creator faz. Uma opção, talvez, seria: no Gameplay armazenar os logs no localStorage, para depois criar um template em "./build-templates" com ReactJS que resgata esses dados. Seria viável ou acha que ficaria muito "gambiarra"?

### Considerações finais

Também posso adicionar os comentários se for o caso. Com esta minha resposta, gostaria apenas de entender melhor se o teste encerrou ou se ele continuará com um refactory após conversarmos melhor sobre os pontos 1 e 3. O que acha?

Agradeço pela resposta.

**Comment by stefanhacks** [comment]
@cafecomlucas 

Então! Quanto à lógica, o seguinte: 

Os resultados não podem ser pré definidos. Deve ser, sim, implementada a lógica que estabelece a matemática pedida. As chances passadas, 33%, 7%, etc., devem aparecer aí. Se quiser um exemplo de como os jogos de cassino funcionam, pode dar uma olhada [neste aqui](https://games.netent.com/video-slots/ozzy-osbourne/).

Quanto aos logs, não precisa ser na mesma tela do gameplay. De fato, deixamos isso em aberto à sua escolha. A sua sugestão é viável.

Sinta-se à vontade de fazer um refactor e repassar em commits futuros.

Abraço!

**Comment by cafecomlucas** [comment]
@stefanhacks 

Quanto a lógica dos resultados, acho que entendi agora. Acabo de fazer um commit com as modificações. O deploy também foi feito. Saberia dizer se agora está de acordo?

Quanto aos logs separados, estou providenciando e faço um novo commit assim que possível (caso queira ver algum status, ainda é possível ver os logs no próprio console do navegador).

Agradeço o retorno.

Abraço!

**Comment by cafecomlucas** [comment]
@stefanhacks 

Complementando o comentário anterior, agora os logs foram configurados para serem gravados no armazenamento local pela aplicação do cocos e lidos em outra página através de uma aplicação React.

Atualizei o README e fiz um novo deploy. Para acessar os logs enquanto joga basta abrir o caminho `/logs` em uma outra aba. Segue abaixo uma imagem de demonstração.

Obrigado pelo feedback, espero que esteja de acordo.

Abraço!

![image](https://user-images.githubusercontent.com/13612412/76258403-41cc0d00-6232-11ea-8ddf-fe15bdd381cd.png)

**Comment by stefanhacks** [comment]
Legal Lucas, lhe daremos o retorno via e-mail num futuro próximo!

Abraço.
